//! DTS Coherent Acoustics **core** decoder (ETSI TS 102 114 V1.6.1, clause 5).
//!
//! Decodes the core substream — up to five full-range channels plus LFE at
//! ≤ 48 kHz — to interleaved f32 PCM so a DTS track can be transcoded to
//! Opus. Extensions are not decoded: XCh/XXCh/X96 data inside the core frame
//! and any DTS-HD extension substream after it are skipped, so a DTS-HD
//! track yields its (lossy) core, which is what legacy DTS decoders play.
//!
//! What is implemented follows the spec's own decoding procedure: the bit
//! stream and primary audio coding headers (Tables 5-1, 5-21), the per-
//! subframe side information (5-28), the audio arrays (5-29) with Huffman,
//! block-code and linear quantisation index decoding, transient-split scale
//! factors, joint intensity coding, front/surround sum-difference decoding,
//! dynamic range control, the 32-band QMF synthesis and the 64×/128× LFE
//! interpolation (Annex C.3). Every table is transcribed from the ETSI text
//! (`tables.rs`, generated by `crates/codec/tools/dts_gen_tables.py`).
//!
//! Two codebooks are missing from every ETSI edition of the spec ("Due to
//! its extensive size, this table is not included here", D.10 — and the DTS
//! patents describe them without printing them), and the licence rule for
//! this decoder forbids taking them from any other decoder's source:
//!
//! - **ADPCM prediction coefficients (D.10.1)**: a subband coded with
//!   `PMODE` = 1 carries prediction residuals, and without the 4096-vector
//!   codebook the prediction cannot be inverted. Such frames are refused by
//!   name ([`DtsError::Unsupported`]) rather than decoded wrongly; the job
//!   layer turns that into "dropped, with the reason". This matters in
//!   practice: ffmpeg's `dca` encoder never predicts, so its streams decode
//!   completely, but a commercial DTS-HD MA track measured on 2026-09-13
//!   (60 s of its core, 5 637 frames) predicted at least one subband in
//!   91 % of frames (3.3 % of all subbands), so most disc-sourced DTS
//!   refuses. Verified against libavcodec on ffmpeg-made vectors to ~1e-6
//!   relative RMS (`crates/codec/tests/dts_core.rs`).
//! - **High-frequency VQ (D.10.2)**: subbands from `VQSUB` up are carried as
//!   a single 10-bit vector index. The spec itself allows ignoring them
//!   ("In case of insufficient MIPS, the VQs for the highest frequency
//!   subbands may be ignored without causing audible distortion", §5.4.3),
//!   so they decode as silence, with one warning per decoder instance. The
//!   same commercial track VQ-coded subbands 28–31 (21–24 kHz) in every
//!   frame.
//!
//! Output order per channel count is the RFC 7845 family-1 order the rest of
//! the audio pipeline uses (`5.1(side)` = FL FR FC LFE SL SR, `2.1` = FL FR
//! LFE), mapped from the core's `AMODE` order. Arrangements the pipeline has
//! no named layout for are refused by name rather than emitted mislabelled.
//!
//! Not applied: dialog normalisation (`DNG`), which is a playback-level
//! adjustment, and the embedded down-mix coefficients.

// The unpacking loops index several per-channel/per-subband arrays by the
// same `ch` / `sb` the spec's pseudocode uses, so they read against it
// line by line; iterator forms would not.
#![allow(clippy::needless_range_loop)]

mod bits;
mod huffman;
mod synth;
pub mod tables;
#[cfg(test)]
mod tests;

use bits::BitReader;
use huffman::SampleCoding;
use synth::{LfeInterp, NUM_SUBBANDS, Qmf};

use crate::audio::{AudioDecoder, AudioError, AudioFrame};

/// Core substream sync word (§5.3), 16-bit big-endian framing — the only
/// framing that occurs inside Matroska/MP4.
pub const CORE_SYNC: u32 = 0x7FFE_8001;

#[derive(Debug, thiserror::Error)]
pub enum DtsError {
    #[error("DTS: frame truncated at bit {at_bit} (wanted {wanted} more bits)")]
    Truncated { at_bit: usize, wanted: u32 },
    #[error("DTS: packet does not start with the core sync word 0x7FFE8001")]
    NoSync,
    #[error("DTS: invalid bitstream: {0}")]
    Invalid(&'static str),
    #[error("DTS: unsupported: {0}")]
    Unsupported(String),
}

impl From<DtsError> for AudioError {
    fn from(e: DtsError) -> Self {
        match e {
            DtsError::Unsupported(_) => AudioError::Unsupported(e.to_string()),
            other => AudioError::Decode(other.to_string()),
        }
    }
}

/// Core sample rates by `SFREQ` (Table 5-5); 0 marks a reserved code.
const SAMPLE_RATES: [u32; 16] = [
    0, 8_000, 16_000, 32_000, 0, 0, 11_025, 22_050, 44_100, 0, 0, 12_000, 24_000, 48_000, 0, 0,
];

/// Full-range channel count per `AMODE` (Table 5-4).
const AMODE_CHANNELS: [usize; 16] = [1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 6, 6, 6, 7, 8, 8];

/// Table 5-27: scale factor adjustment values by `ADJ` index.
const ADJ_TABLE: [f64; 4] = [1.0, 1.125, 1.25, 1.4375];

/// The subband-sample / scale-factor domain is 24-bit PCM: the scale factor
/// tables (D.1) top out at 8 317 638 ≈ 2^23 (138.4 dB), and Annex C writes
/// the QMF and LFE outputs as `int` samples on that same scale.
const OUTPUT_SCALE: f64 = 1.0 / (1u32 << 23) as f64;

/// Maximum primary channels the core carries (§5.4.3: `nPCHS`).
const MAX_CHANNELS: usize = 5;

/// One output channel slot: a core channel index, or the LFE.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Slot {
    Core(usize),
    Lfe,
}

/// Map an `AMODE` (+ LFE) onto a named pipeline layout: `(name, slots)`.
fn output_layout(amode: u32, lfe: bool) -> Result<(&'static str, Vec<Slot>), DtsError> {
    use Slot::*;
    Ok(match (amode, lfe) {
        (0, false) => ("mono", vec![Core(0)]),
        // A+B dual mono, L+R, (L+R)+(L-R) (already sum/difference decoded),
        // LT+RT: two front channels in order.
        (1..=4, false) => ("stereo", vec![Core(0), Core(1)]),
        (1..=4, true) => ("2.1", vec![Core(0), Core(1), Lfe]),
        // C + L + R
        (5, false) => ("3.0", vec![Core(1), Core(2), Core(0)]),
        // C + L + R + S
        (7, false) => ("4.0", vec![Core(1), Core(2), Core(0), Core(3)]),
        // L + R + SL + SR
        (8, false) => ("quad", vec![Core(0), Core(1), Core(2), Core(3)]),
        // C + L + R + SL + SR — the 5.1 core.
        (9, false) => ("5.0(side)", vec![Core(1), Core(2), Core(0), Core(3), Core(4)]),
        (9, true) => ("5.1(side)", vec![Core(1), Core(2), Core(0), Lfe, Core(3), Core(4)]),
        (6, _) => {
            return Err(DtsError::Unsupported(
                "AMODE 6 (L + R + S) has no 3-channel layout with a surround in this pipeline".into(),
            ));
        }
        (0 | 5 | 7 | 8, true) => {
            return Err(DtsError::Unsupported(format!(
                "AMODE {amode} with an LFE channel ({}.1) has no named layout in this pipeline",
                AMODE_CHANNELS[amode as usize]
            )));
        }
        (10..=15, _) => {
            return Err(DtsError::Unsupported(format!(
                "AMODE {amode} ({} full-range channels) needs the XCh/XXCh channel extension, which is not decoded",
                AMODE_CHANNELS[amode as usize]
            )));
        }
        _ => {
            return Err(DtsError::Unsupported(format!(
                "AMODE {amode} is a user-defined channel arrangement"
            )));
        }
    })
}

/// A left/right pair of core channel indices.
type Pair = (usize, usize);

/// Front L/R and surround L/R core channel indices for sum/difference
/// decoding (Annex C.3.5), per `AMODE`.
fn sum_diff_pairs(amode: u32) -> (Option<Pair>, Option<Pair>) {
    match amode {
        1..=4 | 6 => (Some((0, 1)), None),
        5 | 7 => (Some((1, 2)), None),
        8 => (Some((0, 1)), Some((2, 3))),
        9 => (Some((1, 2)), Some((3, 4))),
        _ => (None, None),
    }
}

/// The frame-level fields the decoder acts on (Tables 5-1 and 5-21).
struct FrameHeader {
    total_samples: usize,
    amode: u32,
    sample_rate: u32,
    lossless_steps: bool,
    dynf: bool,
    aspf: bool,
    /// `LFF`: 0 none, 1 → 128× interpolation, 2 → 64×.
    lff: u32,
    filts_perfect: bool,
    sumf: bool,
    sums: bool,
    cpf: bool,
    subframes: usize,
    channels: usize,
    subs: [usize; MAX_CHANNELS],
    vqsub: [usize; MAX_CHANNELS],
    joinx: [usize; MAX_CHANNELS],
    thuff: [u32; MAX_CHANNELS],
    shuff: [u32; MAX_CHANNELS],
    bhuff: [u32; MAX_CHANNELS],
    /// `SEL[ch][n]` for `ABITS` = n+1, n < 10 (Table 5-26).
    sel: [[u32; 10]; MAX_CHANNELS],
    /// `arADJ[ch][n]`, 1.0 unless transmitted.
    adj: [[f64; 10]; MAX_CHANNELS],
}

/// Read the 14-bit `FSIZE` without a full parse, so the reader can be bounded
/// to the frame before anything else is decoded.
fn frame_len_of(buf: &[u8]) -> Result<usize, DtsError> {
    if buf.len() < 8 {
        return Err(DtsError::Truncated {
            at_bit: buf.len() * 8,
            wanted: 64,
        });
    }
    let mut r = BitReader::new(buf);
    if r.bits(32)? != CORE_SYNC {
        return Err(DtsError::NoSync);
    }
    r.bits(1 + 5 + 1 + 7)?;
    Ok(r.bits(14)? as usize + 1)
}

fn parse_header(r: &mut BitReader) -> Result<FrameHeader, DtsError> {
    if r.bits(32)? != CORE_SYNC {
        return Err(DtsError::NoSync);
    }
    let ftype = r.bits(1)?;
    let _short = r.bits(5)?;
    let cpf = r.flag()?;
    let nblks = r.bits(7)?;
    let _fsize = r.bits(14)?;
    let amode = r.bits(6)?;
    let sfreq = r.bits(4)?;
    let rate = r.bits(5)?;
    let _fixed = r.bits(1)?;
    let dynf = r.flag()?;
    let _timef = r.flag()?;
    let _auxf = r.flag()?;
    let _hdcd = r.flag()?;
    let _ext_audio_id = r.bits(3)?;
    let _ext_audio = r.flag()?;
    let aspf = r.flag()?;
    let lff = r.bits(2)?;
    let _hflag = r.flag()?;
    if cpf {
        let _hcrc = r.bits(16)?;
    }
    let filts = r.flag()?;
    let vernum = r.bits(4)?;
    let _chist = r.bits(2)?;
    let _pcmr = r.bits(3)?;
    let sumf = r.flag()?;
    let sums = r.flag()?;
    let _dialnorm = r.bits(4)?;

    if ftype == 0 {
        return Err(DtsError::Unsupported(
            "termination frame (FTYPE = 0, partial subsubframes) — only normal frames are decoded".into(),
        ));
    }
    if nblks < 5 {
        return Err(DtsError::Invalid("NBLKS below 5"));
    }
    let sample_rate = SAMPLE_RATES[sfreq as usize];
    if sample_rate == 0 {
        return Err(DtsError::Invalid("reserved SFREQ code"));
    }
    if lff == 3 {
        return Err(DtsError::Invalid("LFF = 3"));
    }
    if vernum > 7 {
        return Err(DtsError::Unsupported(format!(
            "VERNUM {vernum}: encoder revision incompatible with ETSI TS 102 114 V1.6.1 (spec says mute)"
        )));
    }
    if amode > 9 {
        // Detail comes from the layout mapping; run it now so the error is the named one.
        output_layout(amode, lff > 0)?;
    }

    // Primary audio coding header (Table 5-21).
    let subframes = r.bits(4)? as usize + 1;
    let channels = r.bits(3)? as usize + 1;
    if channels > MAX_CHANNELS {
        return Err(DtsError::Invalid("more than five primary channels in the core"));
    }
    if channels != AMODE_CHANNELS[amode as usize] {
        return Err(DtsError::Invalid("PCHS disagrees with AMODE"));
    }
    let mut h = FrameHeader {
        total_samples: 32 * (nblks as usize + 1),
        amode,
        sample_rate,
        lossless_steps: rate == 0x1F,
        dynf,
        aspf,
        lff,
        filts_perfect: filts,
        sumf,
        sums,
        cpf,
        subframes,
        channels,
        subs: [0; MAX_CHANNELS],
        vqsub: [0; MAX_CHANNELS],
        joinx: [0; MAX_CHANNELS],
        thuff: [0; MAX_CHANNELS],
        shuff: [0; MAX_CHANNELS],
        bhuff: [0; MAX_CHANNELS],
        sel: [[0; 10]; MAX_CHANNELS],
        adj: [[1.0; 10]; MAX_CHANNELS],
    };
    for ch in 0..channels {
        h.subs[ch] = r.bits(5)? as usize + 2;
        if h.subs[ch] > NUM_SUBBANDS {
            return Err(DtsError::Invalid("SUBS above 32 active subbands"));
        }
    }
    for ch in 0..channels {
        h.vqsub[ch] = r.bits(5)? as usize + 1;
        if h.vqsub[ch] > h.subs[ch] {
            return Err(DtsError::Invalid("VQSUB above SUBS"));
        }
    }
    for ch in 0..channels {
        h.joinx[ch] = r.bits(3)? as usize;
        if h.joinx[ch] > ch {
            return Err(DtsError::Invalid("JOINX source channel is not a lower channel"));
        }
    }
    for ch in 0..channels {
        h.thuff[ch] = r.bits(2)?;
    }
    for ch in 0..channels {
        h.shuff[ch] = r.bits(3)?;
        if h.shuff[ch] == 7 {
            return Err(DtsError::Invalid("SHUFF = 7"));
        }
    }
    for ch in 0..channels {
        h.bhuff[ch] = r.bits(3)?;
        if h.bhuff[ch] == 7 {
            return Err(DtsError::Invalid("BHUFF = 7"));
        }
    }
    for ch in 0..channels {
        h.sel[ch][0] = r.bits(1)?;
    }
    for n in 1..5 {
        for ch in 0..channels {
            h.sel[ch][n] = r.bits(2)?;
        }
    }
    for n in 5..10 {
        for ch in 0..channels {
            h.sel[ch][n] = r.bits(3)?;
        }
    }
    // ADJ is transmitted wherever SEL picked a Huffman book.
    for ch in 0..channels {
        if h.sel[ch][0] == 0 {
            h.adj[ch][0] = ADJ_TABLE[r.bits(2)? as usize];
        }
    }
    for n in 1..5 {
        for ch in 0..channels {
            if h.sel[ch][n] < 3 {
                h.adj[ch][n] = ADJ_TABLE[r.bits(2)? as usize];
            }
        }
    }
    for n in 5..10 {
        for ch in 0..channels {
            if h.sel[ch][n] < 7 {
                h.adj[ch][n] = ADJ_TABLE[r.bits(2)? as usize];
            }
        }
    }
    if cpf {
        let _ahcrc = r.bits(16)?;
    }
    Ok(h)
}

/// Per-subframe side information (Table 5-28) that the audio arrays need.
struct SideInfo {
    ssc: usize,
    abits: [[u32; NUM_SUBBANDS]; MAX_CHANNELS],
    tmode: [[u32; NUM_SUBBANDS]; MAX_CHANNELS],
    scales: [[[f64; 2]; NUM_SUBBANDS]; MAX_CHANNELS],
    join_scales: [[f64; NUM_SUBBANDS]; MAX_CHANNELS],
    range: f64,
}

/// One decoded core frame.
struct Decoded {
    /// Bytes consumed (`FSIZE + 1`).
    frame_len: usize,
    /// Interleaved f32 in the pipeline's channel order.
    samples: Vec<f32>,
    channels: usize,
    sample_rate: u32,
    /// Samples per channel.
    frames: usize,
}

pub struct DtsDecoder {
    qmf: Vec<Qmf>,
    lfe: LfeInterp,
    /// Declared by the container; checked against the stream's own header.
    declared_sample_rate: u32,
    declared_channels: u8,
    next_pts_us: Option<i64>,
    hf_vq_warned: bool,
    layout_logged: bool,
}

impl DtsDecoder {
    pub fn new(sample_rate: u32, channels: u8) -> Result<Self, AudioError> {
        if channels == 0 || channels > 6 {
            return Err(AudioError::Unsupported(format!(
                "DTS core decoder handles 1..=6 channels (5.1), container says {channels}"
            )));
        }
        Ok(Self {
            qmf: (0..MAX_CHANNELS).map(|_| Qmf::new()).collect(),
            lfe: LfeInterp::new(),
            declared_sample_rate: sample_rate,
            declared_channels: channels,
            next_pts_us: None,
            hf_vq_warned: false,
            layout_logged: false,
        })
    }

    fn read_scale_index(
        r: &mut BitReader,
        shuff: u32,
        book: Option<&huffman::Codebook>,
        acc: &mut i32,
    ) -> Result<usize, DtsError> {
        let idx = match shuff {
            5 => r.bits(6)? as i32,
            6 => r.bits(7)? as i32,
            _ => {
                // Huffman: the difference from the previous index.
                *acc += book.expect("SHUFF < 5 has a book").decode(r)?;
                *acc
            }
        };
        if shuff >= 5 {
            *acc = idx;
        }
        if idx < 0 {
            return Err(DtsError::Invalid("negative scale factor index"));
        }
        Ok(idx as usize)
    }

    fn scale_lookup(shuff: u32, idx: usize) -> Result<f64, DtsError> {
        let v = if shuff == 6 {
            tables::SCALE_RMS_7BIT.get(idx).copied()
        } else {
            tables::SCALE_RMS_6BIT.get(idx).copied()
        };
        match v {
            Some(v) if v > 0 => Ok(v as f64),
            _ => Err(DtsError::Invalid("scale factor index outside the quantisation table")),
        }
    }

    fn parse_side_info(&mut self, r: &mut BitReader, h: &FrameHeader) -> Result<SideInfo, DtsError> {
        let ssc = r.bits(2)? as usize + 1;
        let psc = r.bits(3)?;
        if psc != 0 {
            return Err(DtsError::Invalid("partial subsubframe (PSC) in a normal frame"));
        }
        let mut pmode = [[false; NUM_SUBBANDS]; MAX_CHANNELS];
        for ch in 0..h.channels {
            for sb in 0..h.subs[ch] {
                pmode[ch][sb] = r.flag()?;
            }
        }
        let mut adpcm = 0usize;
        for ch in 0..h.channels {
            for sb in 0..h.subs[ch] {
                if pmode[ch][sb] {
                    let _pvq = r.bits(12)?;
                    adpcm += 1;
                }
            }
        }
        if adpcm > 0 {
            return Err(DtsError::Unsupported(format!(
                "ADPCM prediction (PMODE = 1 in {adpcm} subbands): the D.10.1 prediction-coefficient \
                 VQ codebook is not published in ETSI TS 102 114, so the residuals cannot be reconstructed"
            )));
        }

        let mut si = SideInfo {
            ssc,
            abits: [[0; NUM_SUBBANDS]; MAX_CHANNELS],
            tmode: [[0; NUM_SUBBANDS]; MAX_CHANNELS],
            scales: [[[0.0; 2]; NUM_SUBBANDS]; MAX_CHANNELS],
            join_scales: [[0.0; NUM_SUBBANDS]; MAX_CHANNELS],
            range: 1.0,
        };

        // ABITS (bit allocation) per non-VQ subband.
        for ch in 0..h.channels {
            let book = huffman::abits_book(h.bhuff[ch]);
            for sb in 0..h.vqsub[ch] {
                si.abits[ch][sb] = match h.bhuff[ch] {
                    5 => r.bits(4)?,
                    6 => r.bits(5)?,
                    _ => book.expect("BHUFF < 5 has a book").decode(r)? as u32,
                };
                if si.abits[ch][sb] > 26 {
                    return Err(DtsError::Invalid("ABITS above 26"));
                }
            }
        }
        // TMODE, only with more than one subsubframe and only where bits are allocated.
        if ssc > 1 {
            for ch in 0..h.channels {
                let book = huffman::tmode_book(h.thuff[ch]);
                for sb in 0..h.vqsub[ch] {
                    if si.abits[ch][sb] > 0 {
                        si.tmode[ch][sb] = book.decode(r)? as u32;
                    }
                }
            }
        }
        // SCALES: one per allocated subband, two if it has a transient; then
        // one per high-frequency VQ subband. Huffman-coded indices are
        // differences accumulated across the channel.
        for ch in 0..h.channels {
            let shuff = h.shuff[ch];
            let book = huffman::scale_book(shuff);
            let mut acc = 0i32;
            for sb in 0..h.vqsub[ch] {
                if si.abits[ch][sb] > 0 {
                    let idx = Self::read_scale_index(r, shuff, book, &mut acc)?;
                    si.scales[ch][sb][0] = Self::scale_lookup(shuff, idx)?;
                    if si.tmode[ch][sb] > 0 {
                        let idx = Self::read_scale_index(r, shuff, book, &mut acc)?;
                        si.scales[ch][sb][1] = Self::scale_lookup(shuff, idx)?;
                    }
                }
            }
            for sb in h.vqsub[ch]..h.subs[ch] {
                let idx = Self::read_scale_index(r, shuff, book, &mut acc)?;
                si.scales[ch][sb][0] = Self::scale_lookup(shuff, idx)?;
            }
        }
        // Joint intensity coding: a code book select, then one scale per
        // subband copied from the source channel.
        let mut join_shuff = [0u32; MAX_CHANNELS];
        for ch in 0..h.channels {
            if h.joinx[ch] > 0 {
                join_shuff[ch] = r.bits(3)?;
                if join_shuff[ch] == 7 {
                    return Err(DtsError::Invalid("JOIN_SHUFF = 7"));
                }
            }
        }
        for ch in 0..h.channels {
            if h.joinx[ch] > 0 {
                let src = h.joinx[ch] - 1;
                let shuff = join_shuff[ch];
                let book = huffman::scale_book(shuff);
                for sb in h.subs[ch]..h.subs[src] {
                    let raw = match shuff {
                        5 => r.bits(6)? as i32,
                        6 => r.bits(7)? as i32,
                        _ => book.expect("JOIN_SHUFF < 5 has a book").decode(r)?,
                    };
                    let idx = raw + 64;
                    let scale = usize::try_from(idx)
                        .ok()
                        .and_then(|i| tables::JOINT_INTENSITY_SCALE.get(i).copied())
                        .ok_or(DtsError::Invalid("joint intensity scale index out of range"))?;
                    si.join_scales[ch][sb] = scale as f64;
                }
            }
        }
        if h.dynf {
            si.range = tables::DRC_MULTIPLIER[r.bits(8)? as usize] as f64;
        }
        if h.cpf {
            let _sicrc = r.bits(16)?;
        }
        Ok(si)
    }

    /// Decode one core frame at the start of `buf`.
    fn decode_frame(&mut self, buf: &[u8]) -> Result<Decoded, DtsError> {
        let frame_len = frame_len_of(buf)?;
        if buf.len() < frame_len {
            return Err(DtsError::Truncated {
                at_bit: buf.len() * 8,
                wanted: ((frame_len - buf.len()) * 8) as u32,
            });
        }
        let mut r = BitReader::new(&buf[..frame_len]);
        let h = parse_header(&mut r)?;
        let (layout_name, slots) = output_layout(h.amode, h.lff > 0)?;
        if !self.layout_logged {
            self.layout_logged = true;
            tracing::info!(
                amode = h.amode,
                lfe = h.lff > 0,
                layout = layout_name,
                sample_rate = h.sample_rate,
                filts = if h.filts_perfect { "perfect" } else { "non-perfect" },
                "DTS core: decoding"
            );
            if h.sample_rate != self.declared_sample_rate || slots.len() != self.declared_channels as usize {
                tracing::warn!(
                    container_rate = self.declared_sample_rate,
                    container_channels = self.declared_channels,
                    stream_rate = h.sample_rate,
                    stream_channels = slots.len(),
                    "DTS core: container metadata disagrees with the bitstream; the bitstream wins"
                );
            }
        }

        let step_table: &[u32; 27] = if h.lossless_steps {
            &tables::STEP_SIZE_LOSSLESS_Q22
        } else {
            &tables::STEP_SIZE_LOSSY_Q22
        };
        let (front_pair, surround_pair) = sum_diff_pairs(h.amode);

        let mut pcm: Vec<Vec<f64>> = (0..h.channels).map(|_| Vec::with_capacity(h.total_samples)).collect();
        let mut lfe_pcm: Vec<f64> = Vec::with_capacity(if h.lff > 0 { h.total_samples } else { 0 });

        for _subframe in 0..h.subframes {
            let si = self.parse_side_info(&mut r, &h)?;
            let nsamples = 8 * si.ssc;
            // samples[ch][sample][subband]
            let mut samples = vec![[[0.0f64; NUM_SUBBANDS]; 32]; h.channels];

            // High-frequency VQ subbands: the index is read, the codebook is
            // not available (D.10.2), the samples stay zero.
            for ch in 0..h.channels {
                for _sb in h.vqsub[ch]..h.subs[ch] {
                    let _vq_index = r.bits(10)?;
                    if !self.hf_vq_warned {
                        self.hf_vq_warned = true;
                        tracing::warn!(
                            "DTS core: high-frequency VQ subbands present; decoded as silence (the D.10.2 \
                             codebook is not published; the spec allows ignoring these subbands)"
                        );
                    }
                }
            }

            // LFE: 2·LFF·nSSC 8-bit samples, then a 7-bit-table scale index.
            let mut lfe_dec: Vec<f64> = Vec::new();
            if h.lff > 0 {
                let n = 2 * h.lff as usize * si.ssc;
                let mut raw = Vec::with_capacity(n);
                for _ in 0..n {
                    raw.push(r.sbits(8)? as f64);
                }
                let idx = r.bits(8)? as usize;
                let scale = tables::SCALE_RMS_7BIT
                    .get(idx)
                    .copied()
                    .filter(|v| *v > 0)
                    .ok_or(DtsError::Invalid("LFE scale index outside the 7-bit table"))?;
                let rscale = scale as f64 * 0.035;
                lfe_dec.extend(raw.iter().map(|v| v * rscale));
            }

            // Audio arrays (Table 5-29).
            for ssf in 0..si.ssc {
                for ch in 0..h.channels {
                    for sb in 0..h.vqsub[ch] {
                        let abits = si.abits[ch][sb];
                        let sel = if (1..=10).contains(&abits) { h.sel[ch][abits as usize - 1] } else { 0 };
                        let coding = huffman::sample_coding(abits, sel)?;
                        let mut q = [0i32; 8];
                        match coding {
                            SampleCoding::None => {}
                            SampleCoding::Huffman(book) => {
                                for v in q.iter_mut() {
                                    *v = book.decode(&mut r)?;
                                }
                            }
                            SampleCoding::Raw { bits } => {
                                for v in q.iter_mut() {
                                    *v = r.sbits(bits)?;
                                }
                            }
                            SampleCoding::Block { levels, bits } => {
                                let mut block = [0i32; 4];
                                for half in 0..2 {
                                    let code = r.bits(bits)?;
                                    huffman::decode_block(code, levels, &mut block)?;
                                    q[half * 4..half * 4 + 4].copy_from_slice(&block);
                                }
                            }
                        }
                        if abits == 0 {
                            continue;
                        }
                        let step = step_table[abits as usize] as f64 / (1u32 << 22) as f64;
                        let tm = if si.tmode[ch][sb] == 0 { si.ssc } else { si.tmode[ch][sb] as usize };
                        let sf = if ssf < tm { si.scales[ch][sb][0] } else { si.scales[ch][sb][1] };
                        let mut scale = step * sf;
                        if let SampleCoding::Huffman(_) = coding {
                            scale *= h.adj[ch][abits as usize - 1];
                        }
                        for (m, v) in q.iter().enumerate() {
                            samples[ch][ssf * 8 + m][sb] = scale * *v as f64;
                        }
                    }
                }
                if (ssf == si.ssc - 1 || h.aspf) && r.bits(16)? != 0xFFFF {
                    return Err(DtsError::Invalid("DSYNC missing at the end of a subsubframe"));
                }
            }

            // Joint intensity coding (Annex C.3.4).
            for ch in 0..h.channels {
                if h.joinx[ch] > 0 {
                    let src = h.joinx[ch] - 1;
                    for sb in h.subs[ch]..h.subs[src] {
                        for s in 0..nsamples {
                            samples[ch][s][sb] = si.join_scales[ch][sb] * samples[src][s][sb];
                        }
                    }
                }
            }
            // Sum/difference decoding (Annex C.3.5); AMODE 3 is coded that way by definition.
            let mut pairs = Vec::new();
            if h.sumf || h.amode == 3 {
                pairs.extend(front_pair);
            }
            if h.sums {
                pairs.extend(surround_pair);
            }
            for (l, rr) in pairs {
                for s in 0..nsamples {
                    for sb in 0..NUM_SUBBANDS {
                        let a = samples[l][s][sb];
                        let b = samples[rr][s][sb];
                        samples[l][s][sb] = a + b;
                        samples[rr][s][sb] = a - b;
                    }
                }
            }
            // Filter bank reconstruction, then dynamic range control.
            let mut out32 = [0.0f64; 32];
            for ch in 0..h.channels {
                for s in 0..nsamples {
                    self.qmf[ch].synthesize(&samples[ch][s], h.filts_perfect, &mut out32);
                    pcm[ch].extend(out32.iter().map(|v| v * si.range));
                }
            }
            if h.lff > 0 {
                let factor = if h.lff == 1 { 128 } else { 64 };
                self.lfe.interpolate(&lfe_dec, factor, &mut lfe_pcm);
            }
        }

        for ch in 0..h.channels {
            if pcm[ch].len() != h.total_samples {
                return Err(DtsError::Invalid("subframes do not add up to NBLKS blocks"));
            }
        }
        if h.lff > 0 && lfe_pcm.len() != h.total_samples {
            return Err(DtsError::Invalid("LFE samples do not add up to NBLKS blocks"));
        }

        let channels = slots.len();
        let mut out = vec![0.0f32; h.total_samples * channels];
        for (slot_idx, slot) in slots.iter().enumerate() {
            let src: &[f64] = match slot {
                Slot::Core(c) => &pcm[*c],
                Slot::Lfe => &lfe_pcm,
            };
            for (i, v) in src.iter().enumerate() {
                out[i * channels + slot_idx] = (v * OUTPUT_SCALE) as f32;
            }
        }
        Ok(Decoded {
            frame_len,
            samples: out,
            channels,
            sample_rate: h.sample_rate,
            frames: h.total_samples,
        })
    }
}

impl AudioDecoder for DtsDecoder {
    fn decode(&mut self, packet: &[u8], pts: i64) -> Result<Vec<AudioFrame>, AudioError> {
        if self.next_pts_us.is_none() {
            self.next_pts_us = Some(pts);
        }
        let mut frames = Vec::new();
        let mut off = 0usize;
        while off + 4 <= packet.len() {
            let sync = u32::from_be_bytes([packet[off], packet[off + 1], packet[off + 2], packet[off + 3]]);
            if sync != CORE_SYNC {
                if off == 0 {
                    return Err(DtsError::NoSync.into());
                }
                // A DTS-HD extension substream or padding follows the core:
                // not decoded, and there is no second core frame behind it.
                break;
            }
            let d = self.decode_frame(&packet[off..])?;
            let pts_us = self.next_pts_us.unwrap_or(0);
            let dur_us = (d.frames as i64 * 1_000_000) / d.sample_rate as i64;
            self.next_pts_us = Some(pts_us.saturating_add(dur_us));
            frames.push(AudioFrame {
                samples: d.samples,
                sample_rate: d.sample_rate,
                channels: d.channels as u8,
                pts: pts_us,
            });
            off += d.frame_len;
        }
        Ok(frames)
    }

    fn flush(&mut self) -> Result<Vec<AudioFrame>, AudioError> {
        // Every core frame decodes to its full block of PCM as it arrives; the
        // QMF delay is inherent to the format and not flushed (matches the
        // spec's decoder, which emits 32·(NBLKS+1) samples per frame).
        Ok(Vec::new())
    }
}
